# Generated by Django 3.2.8 on 2021-10-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comments_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.works'),
        ),
    ]
