# Generated by Django 3.2.8 on 2021-10-25 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0003_alter_comments_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='created_by',
            new_name='user',
        ),
    ]
